version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: kjhman21/node:10.15.3-mocha

command:

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: echo $A
      - run: echo $B
      - run: echo $C

  install_hub:
    <<: *defaults
    steps:
      - run:
          name: "install hub"
          command: |
              type hub || \
              (curl -sSLf https://github.com/github/hub/releases/download/v2.11.1/hub-linux-amd64-2.11.1.tgz | \
                tar zxf - --strip-components=1 -C /tmp && \
                sudo mv /tmp/bin/hub /usr/local/bin/hub)

  tag_verify:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "verify tag and file verison match"
          command: |
            echo "tag version is " $CIRCLE_TAG

            file_version=v$(.circleci/version.sh)
            echo "file version is " $file_version

            if [ $file_version == ${CIRCLE_TAG%-*} ]; then
              echo "verification pass"
            else
              echo "It's not same version."
              #exit 1
            fi

  job_publish:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints: 
            - "36:bc:44:d2:56:9a:74:82:ca:aa:3d:20:4c:36:1f:e9"     
      - checkout
      - run:
          name: "push to release branch"
          command: |
              echo "will push to release branch /release/$CIRCLE_TAG"
              
              git remote -v 
              git branch -a
              #remove above line

              git checkout -b release/${CIRCLE_TAG%-*}
              git push origin release/${CIRCLE_TAG%-*}

  prod_publish:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints: 
            - "36:bc:44:d2:56:9a:74:82:ca:aa:3d:20:4c:36:1f:e9"     
      - checkout
      - run:
          name: "generate tag"
          command: |
              current_version=$(.circleci/version.sh)

              echo "git tag v$current_version"
              git tag v$current_version
              git push origin v$current_version

      - run:
          name: "publish production and delete release branch"
          command: |
              version=$(git log --pretty=format:"%s" -1 | grep -o "v[0-9].\+")
              echo "Publishing a major release! version=$version"
              echo "npm publish --tag "

              #delete release branch. it trigger by merge title
              echo "Delete branch release/${version%-*}"
              git push origin --delete release/${version%-*}


workflows:
  every_commit:
    jobs:
      - test:
          contest: Sample
          filters:
            branches:
              ignore:
                - /release\/.*/
                - master

  tag_trigger:
    jobs:
      - tag_verify:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
            branches:
              ignore: /.*/

      - job_publish:
          requires:
            - tag_verify
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
            branches:
              ignore: /.*/

  publish:
    jobs:
      - prod_publish:
          filters:
            branches:
              only: master



    
