version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: kjhman21/node:10.15.3-mocha

command:

jobs:
  status:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "test whoIam"
          command: |
            echo "whoami: " $(whoami)
            echo  "whereami: " $(pwd)
            echo "ls command: " 
            ls -al
            echo "git branch: "
            git branch
  
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm test


workflows:
  every_commit:
    jobs:
      - status
      - test

